



datasource:
  url: jdbc:mysql://172.16.0.31:3306/tiaodan_spider?useUnicode=true&amp;characterEncoding=UTF-8
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: gozapdev

cagetory:
  words:
    fileDir:
      souhu: /home/xiaoming/newsLearn/news_train_souhu/
      chouti: /home/xiaoming/newsLearn/news_train_chouti/

redis:
  host: 172.16.3.102
  port: 6382

app:
  profile: dev
  name: chouti-analyse
  FeedbackBaseUrl: http://git.chouti.com/api/v3/projects/11/issues
  PrivateToken: -FRkJHxJNsh-GkAYRrga

server:
  port: 1088

context:
  listener:
    classes: com.chouti.analyse.configure.AppListener





