



datasource:
  url: *************************************useUnicode=true&amp;characterEncoding=UTF-8
  driverClassName: com.mysql.jdbc.Driver
  username: ********
  password: ********

cagetory:
  words:
    fileDir: /home/xiaoming/newsLearn/news_train_souhu/

redis:
  host: ************
  port: ********

app:
  profile: dev
  name: test-analyse
  FeedbackBaseUrl: ********************88
  PrivateToken: -FRkJHxJNsh-GkAYRrga

server:
  port: 1088

context:
  listener:
    classes: com.chouti.analyse.configure.AppListener





